### DISCUSSION TITLE
Table and Range Input styles broken

### DISCUSSION THREAD

**Discussion by solutionsinurarea** [ameinhardt/unocss-preset-daisy#11] [Show and tell]
Thanks for this preset, I was surprised how well it worked out of the box but I did find a couple issues:

### Table
Debugging the style sheet for a table component, most of the conditional styles are there (:where selector) but not the base styles.
Expected:
```css
.table {
    position: relative;
    width: 100%;
    border-radius: var(--rounded-box, 1rem);
    text-align: left;
    font-size: .875rem;
    line-height: 1.25rem
}
```

Generated:
```css
.table {
    display: table;
}
```

### Range Input
The slider-thumb pseudo component is displaced on the y axis.

Wouldn't mind contributing if you have any ideas or hints as to why this could happen.
